### PR TITLE
Anywidget

### PR DESCRIPTION
**Pull request by justinlaughlin**
### Context
* Jupyter has made a lot of breaking changes recently ([1](https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html), [2](https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html)) which seems to have broken our plugin:
  * Binder notebooks aren't working
  * Plugin doesn't work on a fresh install
  * I *think* if dependencies are set to certain versions the plugin can work (I'm not certain but I think that is why the `Colab` notebooks still work?); I haven't been able to replicate
* We have been using the javascript widget cookiecutter template. I tried transferring over to the latest recommended templates (`Copier` typescript template) but could not get it to work. 
* From [this cookiecutter](https://github.com/jupyter-widgets/widget-cookiecutter?tab=readme-ov-file) I found out about [anywidget](https://anywidget.dev/) which seems to abstract away most of the widget complexity. 
* This branch is a rewrite of our widget using `anywidget` and can be defined using only 1) the [emscripten compiled glvis hosted on npm](https://www.npmjs.com/package/glvis/v/0.6.3), 2) [a single javascript file](https://github.com/GLVis/pyglvis/blob/anywidget/glvis/widget.js), and 3) [a single python file](https://github.com/GLVis/pyglvis/blob/anywidget/glvis/widget.py).
* We won't need the [glvis-jupyter npm repo](https://www.npmjs.com/package/glvis-jupyter).
* In my opinion, `anywidget` will be a _much_ cleaner implementation than any of the alternatives available at the moment
* There are large visualization packages that also use `anywidget` (e.g. [pyobsplot](https://github.com/juba/pyobsplot/blob/main/src/pyobsplot/widget.py))
* (This is true for all widgets now, I believe) The widget is pip installed like any other normal python package, and doesn't require steps from before such as `jupyter nbextension enable`.
* The work in this branch is related to [Issue 43](https://github.com/GLVis/pyglvis/issues/43)

### Notebooks
I haven't tested much beyond our example notebooks, but they seem to all be working (also, I have not been able to run the widget except through `Colab` otherwise). I updated the Binder badges on this branch and they seem to work, feel free to test it out. Once this is pushed to `pypi` it will affect the Colab notebooks so I'm holding off on that for now.

### CODE REVIEW

**Comment by justinlaughlin** [comment]
This changes/deletes a lot of things so I'm converting to draft for now until there is some feedback

**Comment by tzanio** [comment]
@justinlaughlin do you understand why we get this conflicts and how to resolve them?

Screenshot 2024-06-24 at 3 57 42 PM

**Comment by justinlaughlin** [comment]
> @justinlaughlin do you understand why we get this conflicts and how to resolve them?
> 
> Screenshot 2024-06-24 at 3 57 42 PM

It looks like `package-lock.json` got updated in `main` while this PR deletes `package-lock.json`. A lot of files including this one are deleted because they are no longer necessary thanks to anywidget. `glvis/widget.js` (which pulls from the `npm` mirror of `glvis-js`) contains all of the necessary javascript. There is a [diagram](https://github.com/GLVis/pyglvis/blob/anywidget/README.md#-development) in this branch's README that might be helpful.

I submitted another commit which just deletes `package-lock.json`

**Review by tzanio — APPROVED** [review]
Thanks for updating this @justinlaughlin !

**Comment by justinlaughlin** [comment]
Regarding [6ba5116](https://github.com/GLVis/pyglvis/pull/44/commits/6ba51160a235966e56d842b9461346878e955639), it turns out you can simply point to `github` instead of `npm` using `esm`. From what I tested it seems to work. This simplifies things a lot as we no longer need to host the `npm` mirror of `glvis-js` 😄.

**Pull request merged**
